"""Audit stage: what the source collection gets wrong, published for a reader.

Part of the point of an atlas is that an independent index is the only place a
source's own mistakes become visible. This finds them, describes them
specifically enough to act on, and regenerates a section of `docs/about.html`
between the AUDIT markers.

Modelled on `../e-bharatisampat-atlas/pipeline/audit.py`, which was in turn
modelled on the wikisource sibling -- the conventions are lifted deliberately so
the three projects stay legible to each other. None of their checks transfer;
those audit a database-backed catalogue and a MediaWiki, and this is a
hand-maintained static site.

## Standing rules

**It never mutates anything.** Not the source, not `data/`, not `tree.json`. An
audit finding is a thing for a human to look at, never an auto-correction. The
only file it writes is its own region of `about.html`.

**Every published number is re-derived by the run that publishes it.** The
failure this repo keeps hitting is a measured figure going stale in prose --
CLAUDE.md says it outright ("Don't cite a notes figure as fact -- re-derive
it"), and the About page had drifted to quoting `shivarahasya` at 728 when the
corpus said 784. An About page is the worst place for that because it looks
authoritative. Hence no baked-in constants to compare against.

## Entirely offline

Every check reads a file in `data/`, so the audit needs no network, no
credentials and no rivulet. It is free to run, and running it is the only way a
published figure gets re-derived.

## The checks

Five upstream defects, plus one of our own:

1. **Listed but not served** -- the catalogue links it, the site 404s it.
2. **Malformed catalogue hrefs** -- a space in a path, a `.inf` target.
3. **No Devanagari title** -- `title_deva` is the only transliterable name a
   document has (`title` is ad-hoc romanization, `doc_id` is ITRANS), so a
   document without one cannot be displayed in a reader's chosen script.
4. **Unparseable `Latest update`** -- free text, and some of it is corrupt
   (`April 4, 20R2613`). The corpus's only record of its own dates; an earlier
   copy can stand in for the growth curve, but not fix the field.
5. **Incomplete download sets** -- 9,753 of 9,756 carry all seven format links.
6. **Dead scanned-source links** -- checked by `make check-scans`.
7. **Documents the listing axis drops** -- OURS, not the site's. Reads zero
   since 2026-08-25; kept as a guard. See `find_unlisted_documents`.

Only the first five are rendered. Those are things sanskritdocuments.org could
fix; the seventh is a bug in this pipeline, and filing it under "problems that
should be fixed on sanskritdocuments.org" would blame the site for our own key
format. It is not published separately either -- the page is about the source
collection, so our own defects print to the console instead.

    make audit                # the checks, to the console
    make audit-update-about   # and rewrite the About region
"""

import argparse
import collections
import datetime
import html
import json
import re
from pathlib import Path

from pipeline import parse_snapshot
from pipeline.build_changelog import (corpus_date, load_attestations,
                                      parse_update)
from pipeline.config import (CATALOGUE_PATH, DOCS_DATA_DIR, DUMP_2020_DATE,
                             DUMP_2020_INVENTORY_PATH, INVENTORY_PATH,
                             REPO_ROOT, SCAN_LIVENESS_PATH, SCANS_PATH,
                             SITE_INVENTORY_PATH, SITE_LISTINGS_PATH,
                             SITE_SIZES_PATH, SNAPSHOT_DATE, TEXT_LOG_PATH)

SITE_ROOT = "https://sanskritdocuments.org"

ABOUT_HTML_PATH = REPO_ROOT / "docs" / "about.html"

AUDIT_START_MARKER = (
    "<!-- AUDIT:START -- generated by `python -m pipeline.audit --update-about`; "
    "do not hand-edit between these markers -->"
)
AUDIT_END_MARKER = "<!-- AUDIT:END -->"

TOPIC_FOLDERS_START_MARKER = (
    "<!-- TOPIC_FOLDERS:START -- generated by `python -m pipeline.audit "
    "--update-about`; do not hand-edit between these markers -->"
)
TOPIC_FOLDERS_END_MARKER = "<!-- TOPIC_FOLDERS:END -->"

# Every spliced region, by name. Both are generated wholesale, unlike the
# `data-stat` figures, which are substituted in place inside authored prose.
MARKERS = {
    "AUDIT": (AUDIT_START_MARKER, AUDIT_END_MARKER),
    "TOPIC_FOLDERS": (TOPIC_FOLDERS_START_MARKER, TOPIC_FOLDERS_END_MARKER),
}

# Figures this audit cannot compute itself. `check_scans` measures scan
# liveness on its own schedule and stamps the date it did so; on a machine
# without that cache the figure is absent from `stats`, and `update_intro_stats`
# leaves whatever the page publishes rather than blanking a number it did not
# measure.
EXTERNAL_STATS = frozenset({"scans_checked"})

# Figures only the 2020 mirror can measure. It is local-only -- gitignored, and
# absent on a fresh checkout -- so like EXTERNAL_STATS these keep whatever the
# page already publishes rather than being blanked or recomputed to a wrong
# value from a corpus that cannot see the mirror.
MIRROR_STATS = frozenset({"attested_pulled_back",
                          "attested_pulled_pre2020_pct",
                          "attested_pulled_mid_pct"})

# How many examples a finding lists before it stops. A finding is meant to be
# actionable, not exhaustive: 76 links is a list someone can work through, 9756
# is a data dump that makes the page unloadable.
MAX_EXAMPLES = 60

# `~<hash>`, the suffix `fetch_text` appends to disambiguate two documents whose
# ids differ only by letter case -- macOS and Windows collapse those into one
# file. Stripping it recovers the id the site itself uses.
CASE_SUFFIX_RE = re.compile(r"~[0-9a-f]{6}$")


# --- loading ----------------------------------------------------------------


def _jsonl(path, what):
    if not path.exists():
        raise SystemExit(
            f"{path} is missing -- run `make {what}` first"
        )
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def load_documents(path=SITE_INVENTORY_PATH):
    return _jsonl(path, "parse-site")


def load_inventory_meta(path=SITE_INVENTORY_PATH):
    """Corpus-level figures the folded inventory cannot answer.

    Written beside the inventory by `parse_snapshot`. Two figures, both
    destroyed by parsing rather than merely absent from it:

    `raw_category_spellings`   the count before the fold. `site_inventory.jsonl`
                               holds canonical spellings only, so 366 -> 317 is
                               a one-way trip and the pre-fold number has to be
                               carried rather than recomputed.
    `source_fields`            how many fields the site's own `inf` block uses
                               (`inf_keys` before folding its four typo keys).
                               Every record has the same keys -- the ones
                               `parse_page` maps -- so the source's vocabulary,
                               including what we extract nothing from, is gone
                               by the time a record exists. Recorded but not
                               published: nothing on the About page quotes it,
                               so it carries no `data-stat` tag.

    Missing file is a hard error like any other input -- a stale About page is
    exactly what the data-stat contract exists to prevent, and silently
    defaulting to zero would publish a wrong figure rather than fail loudly.
    """
    meta = parse_snapshot.meta_path_for(path)
    if not meta.exists():
        raise SystemExit(f"{meta} is missing -- run `make parse-site` first")
    return json.loads(meta.read_text(encoding="utf-8"))


def load_listings(path=SITE_LISTINGS_PATH):
    return _jsonl(path, "parse-listings-site")


def load_catalogue(path=CATALOGUE_PATH):
    return _jsonl(path, "fetch-metadata")


def load_sizes(path=SITE_SIZES_PATH):
    return _jsonl(path, "count-sizes")


def load_scans(path=SCANS_PATH):
    """Scan links are optional: a machine without `make parse-scans` still
    audits everything else rather than refusing to run."""
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def load_liveness(path=SCAN_LIVENESS_PATH):
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def fetch_ceiling(path=TEXT_LOG_PATH):
    """The newest `fetched_at` in the journal, as a date ceiling for parsing.

    `parse_update` clamps to this: a `Latest update` later than the day we
    fetched the page is an upstream typo (2027 and 2029 both appear), not a
    date. Derived from the journal for the same reason `build_tree` stamps
    `__content_version__` from it -- a constant here would silently rewrite
    every genuinely-recent document.
    """
    newest = ""
    if path.exists():
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                fetched = json.loads(line).get("fetched_at") or ""
                if fetched > newest:
                    newest = fetched
    if not newest:
        return datetime.datetime.now(datetime.timezone.utc)
    return datetime.datetime.fromisoformat(newest.replace("Z", "+00:00"))


def observed_on(rows):
    """The day a networked probe last actually asked, as `YYYY-MM-DD`.

    Every probe stamps each row it writes with `checked_at`, so the cache
    carries its own currency and nothing has to be told when it ran. The newest
    wins: a resumed or partial run leaves older rows beside newer ones, and the
    honest claim is the most recent observation, not the oldest.

    Returns `None` when the cache is empty or predates stamping -- callers
    publish the figure without a date rather than inventing one.

    Why this exists: a dead-scan count is a measurement of a moment, and
    `check_scans` runs on its own schedule -- its cache was 2.5 weeks older
    than the corpus when this was written. An undated figure hides that, so
    the stamp travels with the number it qualifies.
    """
    stamps = [r.get("checked_at") or "" for r in rows]
    newest = max((s for s in stamps if s), default="")
    return newest[:10] or None


def base_id(doc_id):
    """The site's own id for a document, with our collision suffix removed."""
    return CASE_SUFFIX_RE.sub("", doc_id)


# --- checks -----------------------------------------------------------------
#
# Each is a pure function returning a dict. The registry at the foot of the
# module pairs it with its renderer; adding a check is one entry there plus the
# two functions, rather than a new positional parameter threaded through three
# signatures (which is what the wikisource sibling does, and why its
# `render_audit_html` takes thirteen arguments).


def find_missing_documents(documents, catalogue, listings=()):
    """Documents the site's own indexes link but no longer serve.

    Our fetch got a 404 for each. These are the site disagreeing with itself,
    and among the few findings it could see without our help.

    **Both indexes carry every one.** The site publishes two independent ones --
    20 location pages (`/doc_shiva/`) and 87 listing pages
    (`/sanskrit/shiva/`) -- and all 25 dead links appear on both, which is
    consistent with the two agreeing exactly on all 9781 documents they name.
    So this is not one stale index shadowing a corrected one; the rot is shared.

    The listing pages naming each are attached, since those are the pages a
    maintainer would edit; the location is already in the doc_id.
    """
    held = {base_id(d["doc_id"]) for d in documents}
    missing = sorted({r["doc_id"] for r in catalogue} - held)
    on_listing = collections.defaultdict(list)
    for row in listings:
        for doc_id in row.get("doc_ids") or []:
            if doc_id not in held:
                on_listing[doc_id].append(row["slug"])
    return {
        "ids": missing,
        "count": len(missing),
        "by_location": collections.Counter(d.split("/")[0] for d in missing),
        "on_listing": {k: sorted(v) for k, v in on_listing.items()},
        # How many are named by a listing page as well as their location page.
        "on_both": sum(1 for d in missing if d in on_listing),
    }


def find_malformed_hrefs(catalogue):
    """Catalogue entries whose href is not a document path at all.

    Bad links on the site's own listing pages -- a literal space in one, a
    `.inf` target in the other. They inflate the site's own count by two, and
    the space nearly killed our fetch: `http.client.InvalidURL` is a
    `ValueError`, caught by neither the `HTTPError` nor the `URLError` handler.
    """
    bad = sorted(
        r["doc_id"] for r in catalogue
        if " " in r["doc_id"] or r["doc_id"].endswith(".inf")
    )
    return {"ids": bad, "count": len(bad)}


def find_missing_deva_titles(documents):
    """Documents carrying no Devanagari title, and those whose one is derived.

    `title_deva` is the ONLY one of a document's three names that can be
    transliterated. `title` is the site's free-text English label, and the
    `doc_id` stem only LOOKS like ITRANS -- real ITRANS reproduces it for 3.4%
    of documents, the site cannot write n~/N~ at all, and it spells the
    retroflex sibilant `shh` where ITRANS wants `Sh` (`vishhnu`, not `viShNu`).
    See notes/site-structure.md.
    Feeding `title` to a converter is a silent no-op -- no Devanagari code
    points, string returned unchanged, no error -- which was a real frontend
    bug until 2026-08-18. Without `title_deva` a document cannot render in the
    reader's chosen script at all.

    **The count is the SOURCE's gap, measured before our repair.** Since
    2026-08-28 a document whose page carries no Devanagari banner takes one
    rebuilt from its `itxtitle` (see parse_snapshot.reconstruct_deva), which
    fills `title_deva` -- so testing that field for emptiness measures what
    survives the fallback, not what sanskritdocuments.org is missing. It read 0
    from 2026-08-28 to 2026-09-07 for exactly that reason, reporting a clean
    source while 76 documents still had no title on the page. A document counts
    here if the site did not supply the title, whether or not we reconstructed
    one.

    `unrendered` is the residue that matters to a reader: no banner title AND
    no usable rebuild, so the document can only ever display as English.

    A reconstruction is not equivalent to a banner title. The site's
    romanization is not a real transliteration scheme, so the rebuild is an
    approximation -- lossy in the nasals it cannot express -- where a banner
    title is exact, and the `itxtitle` is sometimes a shorter variant of the
    banner title.
    """
    missing = [d for d in documents
               if d.get("title_deva_reconstructed")
               or not (d.get("title_deva") or "").strip()]
    ids = sorted(d["doc_id"] for d in missing)
    unrendered = sorted(d["doc_id"] for d in missing
                        if not (d.get("title_deva") or "").strip())
    return {"ids": ids, "count": len(ids),
            "unrendered": unrendered, "unrendered_count": len(unrendered)}


def find_unparseable_dates(documents, ceiling):
    """Documents whose `Latest update` will not parse.

    The field is hand-typed free text and the parser is deliberately forgiving
    (`Dec.`, `Julu`, `11-Feb-2015`, `January 5,2005` all resolve). What is left
    is either blank or corrupt -- `April 4, 20R2613`, `RFebruary 20, 2025`.

    This no longer means the document falls off the growth curve: attestation
    against the earlier corpora dates all of them (`bad_dates_rescued`). It is
    still a defect worth reporting -- the field is the corpus's own record of
    itself, and reconstructing it from a copy is not the same as it being
    right.

    Blank and corrupt are reported apart: one is an absence the site could
    fill, the other a typo it could fix, and they are different jobs.
    """
    blank, corrupt = [], []
    for doc in documents:
        raw = (doc.get("latest_update") or "").strip()
        if parse_update(raw, ceiling):
            continue
        (blank if not raw else corrupt).append((doc["doc_id"], raw))
    return {
        "blank": sorted(blank),
        "corrupt": sorted(corrupt),
        "count": len(blank) + len(corrupt),
    }


def find_incomplete_downloads(documents):
    """Documents not carrying the full set of seven format links.

    Nearly every document is published as its ITX source plus generated PDFs in
    Devanagari, Tamil, Telugu, Kannada and Gujarati. Where the set is short,
    the site is offering a format it does not have -- or, for the two carrying
    nothing at all, no download route whatsoever.
    """
    short = sorted(
        (d["doc_id"], len(d.get("downloads") or {}))
        for d in documents
        if len(d.get("downloads") or {}) < 7
    )
    return {"items": short, "count": len(short)}


def find_dead_scans(scans, liveness):
    """Scanned sources the site links that no longer resolve.

    Counted by STEM, not URL: page-anchored links (`/page/n170/mode/1up`)
    differ per document while naming one book, so counting URLs would report
    one dead volume many times over.

    Note what a scan link is and is not. The site never claims a scan is the
    exemplar its e-text was encoded from -- the same volume is cited by every
    text excerpted from it, and four consecutive entries on one listing page
    carry byte-identical sets of sixteen links. A scan is a printed witness of
    this text somewhere, and a dead one is a citation that has rotted.
    """
    if not liveness:
        return {"stems": [], "count": 0, "links": 0, "docs": 0,
                "by_kind": collections.Counter(), "unchecked": True,
                "checked_at": None}
    dead = {r["stem"]: r for r in liveness if r.get("status") != 200}
    stranded = [s for s in scans if s["stem"] in dead]
    return {
        "stems": sorted(dead),
        "count": len(dead),
        "links": len(stranded),
        "docs": len({s["doc_id"] for s in stranded if s["doc_id"]}),
        "by_kind": collections.Counter(r["kind"] for r in dead.values()),
        "detail": dead,
        "unchecked": False,
        # Not today: this is `check_scans`' observation, and it runs on its own
        # schedule. Dating it to the audit would claim a freshness the run has
        # not got -- the liveness cache was 2.5 weeks old when this was added.
        "checked_at": observed_on(liveness),
    }


def find_suppressed_listings(listings):
    """Listing pages this Atlas does not show, because the site duplicates them.

    Two kinds, both decided in `parse_listings.dedupe_aliases` and recorded on
    the surviving row rather than re-derived here -- the suppression and the
    finding must never be able to disagree:

    - a **byte-identical copy**: `/sanskrit/vishhnu/` returns the
      `/sanskrit/vishnu/` page, same bytes, two URLs.
    - a **strict subset**: `/sanskrit/giitaa/` lists 135 documents, all of them
      among `/sanskrit/gita/`'s 138 and in the same order.

    Rendering either put a row in the tree that told a reader nothing and
    double-counted its documents in the axis total. Suppressing them silently
    would be worse, though: an Atlas showing 85 pages where the site's sitemap
    says 87 owes the reader those two names.

    Kept slugs are the saner spelling where the site offers a choice -- `vishnu`
    over `vishhnu`, `gita` over `giitaa`, `shh`/`ii` being the site's own
    invention rather than any transliteration scheme.
    """
    items = []
    for row in listings:
        for alias in row.get("aliases") or []:
            items.append({
                "alias": alias,
                "kept": row["slug"],
                "note": (row.get("alias_notes") or {}).get(alias, "duplicate of"),
            })
    return {"items": sorted(items, key=lambda i: i["alias"]), "count": len(items)}


def find_unlisted_documents(documents, listings):
    """Documents that reach no listing page -- OUR bug, not the site's.

    Reads zero since 2026-08-25, and is kept as a standing guard because it
    caught a real 34-document hole once and would catch its return.

    That hole: two documents whose ids differ only by letter case
    (`gurvaShTakam` / `gurvashtakam` -- case is meaningful in ITRANS) collapse
    to one file on macOS and Windows, so `fetch_text` disambiguates the
    FILENAME with a `~<hash>` suffix. `parse_snapshot` then built `doc_id`
    from that filename, and since `site_listings.jsonl` records the id the SITE
    uses -- which has no suffix -- the join missed and all 34 fell off the
    topics axis.

    The fix was to strip the suffix where `doc_id` is minted, so a filesystem
    workaround never becomes a document's identity; `stem` still carries it,
    because that is what opens the file. Matching on a `base_id()` at each join
    was the alternative, and is worse -- it leaves the wrong id in the data and
    obliges every future consumer to remember the same unfolding.

    A nonzero count here means an id is reaching the tree in a spelling the
    site does not use.
    """
    listed = set()
    for row in listings:
        listed.update(row.get("doc_ids") or [])
    unlisted = sorted(d["doc_id"] for d in documents if d["doc_id"] not in listed)
    suffixed = [d for d in unlisted if CASE_SUFFIX_RE.search(d)]
    pairs = collections.defaultdict(list)
    for doc_id in suffixed:
        pairs[base_id(doc_id).lower()].append(doc_id)
    return {
        "ids": unlisted,
        "count": len(unlisted),
        "suffixed": len(suffixed),
        "pairs": dict(sorted(pairs.items())),
        "explained": len(suffixed) == len(unlisted),
    }


# --- published figures ------------------------------------------------------


# The rows of the Metadata Fields table, in the order they are published --
# richest first, which is also the order that makes the table's point: the
# site fills in what identifies a text and thins out toward what describes it.
#
# **The rule, stated so it stops being implicit.** A row here is an
# `<pre class="inf">` key that (a) the site fills in per document -- it varies
# across the corpus and says something about *this* text -- and (b) the parser
# actually extracts, so the number is measurable rather than guessed.
#
# What that rule excludes, and why each is a deliberate absence rather than an
# oversight -- the distinction this list failed to make until 2026-09-07, when
# nine extracted-nowhere fields were found sitting silently outside it:
#
#   ours, not the site's   `source_url` and `itxtitle` are derived rather than
#                          catalogued, and `sublocation` is upstream noise that
#                          merely repeats the location (see the 2026-08-24
#                          entry in `notes/scratch/todo.md`). Publishing
#                          coverage for these would describe our parser.
#   boilerplate            `Site access` is one site URL on all 9,756 documents
#                          (two spellings, http and https) and `Send
#                          corrections to` is one contact address on 9,750
#                          (thirteen spellings of the same mailbox). Both are
#                          the site's footer, printed per page; neither is a
#                          fact about the text, so a 100% row for either would
#                          measure the template.
#   the same field twice   `File name`, `Text title`, `engtitle` and `Location`
#                          restate `stem`, `title` and `location`, which the
#                          record already carries from elsewhere on the page.
#
# Order is richest first, which is also the order that makes the table's point:
# the site fills in what identifies a text and thins out toward what describes
# it. Hand-sorted -- re-check it when coverage moves.
COVERAGE_FIELDS = [
    "title", "language", "categories", "title_deva", "latest_update",
    "subject", "proofread_by", "indexextra", "description",
    "transliterated_by", "author", "subdeity", "acknowledge_permission",
    "texttype", "source", "translated_by", "subcategory",
]

# field -> the record flag meaning "this value was synthesized, not read off
# the page". A flagged value is not coverage: the table reports what the source
# fills in, and counting our own fallback republishes the pipeline as the site.
DERIVED_FROM = {"title_deva": "title_deva_reconstructed"}


def field_coverage(documents):
    """`cov_<field>` / `covpct_<field>` for every field the page quotes.

    Generated from one list rather than written out, so tagging a new field in
    the prose is a one-line change here.

    "Covered" is non-empty after stripping, and `categories` is a list rather
    than a string -- a bare `.strip()` raises on it, so emptiness is tested
    per-type instead.

    **A reconstructed value is not coverage.** This table measures what
    sanskritdocuments.org fills in, so a value the pipeline rebuilds must not
    count toward it. `title_deva` is the case: 76 documents carry no Devanagari
    title, and `parse_snapshot.reconstruct_deva` approximates one from the
    `itxtitle` field, flagging it `title_deva_reconstructed`. That is not the
    same kind of value -- the source romanization is not a real scheme, so the
    rebuild is lossy where every banner-read title is exact.

    Counting them published `title_deva` at 100.0% from 2026-08-28 (when the
    fallback landed) to 2026-09-07: 9,680 the day before, with nothing about the
    source changed. DERIVED_FROM names the flag that disqualifies a value; add
    an entry whenever a new field gains a fallback.
    """
    stats = {}
    total = len(documents)
    # The row count itself, so the prose above the table cannot quote a
    # different number than the table shows. Counted here rather than typed
    # because adding to COVERAGE_FIELDS must move both together.
    stats["metadata_fields"] = len(COVERAGE_FIELDS)
    for field in COVERAGE_FIELDS:
        derived_flag = DERIVED_FROM.get(field)
        n = 0
        for doc in documents:
            if derived_flag and doc.get(derived_flag):
                continue
            value = doc.get(field)
            if isinstance(value, list):
                n += bool(value)
            else:
                n += bool((value or "").strip())
        stats[f"cov_{field}"] = n
        stats[f"covpct_{field}"] = round(n / total * 100, 1)
    return stats


# Punctuation, addresses and case vary between the two credit lines for the
# same person ("Ruma Dewan" vs "ruma dewan ruma at example.com"), so equality
# is tested on letters alone, with any address stripped first. Containment
# counts as a match because one line is often the other plus a second name.
_CREDIT_ADDRESS_RE = re.compile(r"\S+@\S+|\S+\s+at\s+\S+\s+dot\s+\S+")
_CREDIT_KEEP_RE = re.compile(r"[^a-z ]")


def _credit_key(value):
    value = _CREDIT_ADDRESS_RE.sub(" ", (value or "").lower())
    return " ".join(_CREDIT_KEEP_RE.sub(" ", value).split())


def credit_stats(documents):
    """Who is named for getting a text into the corpus, and how often.

    **`proofread_by` is the input credit, not a checking step**, and the
    figures here are what says so: `credit_sole` documents name that person and
    nobody else. Someone typed each of those, so on a volunteer archive whose
    credit line exists to thank the person who did the work, that person is the
    one named. `transliterated_by` is a second hand where a second hand was
    involved -- it appears on fewer than half the corpus, and agrees with the
    input credit `credit_same_pct` of the time it appears at all.

    Named on the About page rather than left as a reading of the field labels,
    because the labels invite the opposite reading and nothing else on the page
    corrects it.
    """
    sole = both = same = 0
    for doc in documents:
        proofreader = (doc.get("proofread_by") or "").strip()
        translit = (doc.get("transliterated_by") or "").strip()
        if proofreader and not translit:
            sole += 1
        elif proofreader and translit:
            both += 1
            a, b = _credit_key(proofreader), _credit_key(translit)
            if a and b and (a == b or a in b or b in a):
                same += 1
    return {
        "credit_sole": sole,
        "credit_both": both,
        "credit_same_pct": round(same / both * 100, 1) if both else 0.0,
    }


def _and_list(parts):
    """"a", "a and b", "a, b, and c" -- for stats whose value is a name list.

    A name list is a `str` stat, so it reaches the page through `_fmt`
    untouched; the joining has to happen here, at the computation site, like
    every other preformatted figure.
    """
    parts = list(parts)
    if len(parts) <= 2:
        return " and ".join(parts)
    return f"{', '.join(parts[:-1])}, and {parts[-1]}"


def intro_stats(documents, listings, catalogue, sizes, scans, liveness,
                findings, corpus_date_str):
    """Every figure the hand-written prose quotes, re-derived.

    Returns a flat `{key: int|float}`. The type IS the format contract --
    `_fmt` gives an int thousands separators and a float one decimal -- so a
    figure that wants a whole number says so by being `round(x)` here, never by
    loosening `_fmt`.
    """
    total = len(documents)
    stats = {"total": total, "catalogue": len(catalogue)}

    # Axis 1: the canonical folder (the site's `Location`), one per document.
    locations = collections.Counter(d["location"] for d in documents)
    stats["folders"] = len(locations)
    stats["folders_misc"] = sum(1 for loc in locations if "z_misc" in loc)
    stats["folders_nonmisc"] = stats["folders"] - stats["folders_misc"]

    # Axis 2: the site's own topic pages, freely overlapping.
    placements = collections.Counter()
    for row in listings:
        for doc_id in row.get("doc_ids") or []:
            placements[doc_id] += 1
    listed = [placements[d["doc_id"]] for d in documents if d["doc_id"] in placements]
    # The pages we SHOW. The site publishes two more that duplicate others --
    # `find_suppressed_listings` names them, and the About page says so where it
    # quotes this number.
    stats["topic_pages"] = len(listings)
    stats["topic_pages_suppressed"] = findings["suppressed"]["count"]
    stats["topic_pages_published"] = (
        len(listings) + findings["suppressed"]["count"])
    # ...and NAME them. Two prose stats rather than one tag per slug, so the
    # contract holds however many aliases the site grows: each is a rendered
    # phrase, already formatted (`_fmt` passes a str through), and the pair is
    # ordered the same way so "giitaa and vishhnu" lines up with "gita and
    # vishnu" read in the same order.
    suppressed = findings["suppressed"]["items"]
    stats["topic_pages_suppressed_names"] = _and_list(
        f"/sanskrit/{i['alias']}/" for i in suppressed)
    stats["topic_pages_suppressed_kept"] = _and_list(
        f"/sanskrit/{i['kept']}/" for i in suppressed)
    # No `on_topics`/`off_topics` here on purpose. The axes reach the same
    # 9,756 documents, so both figures are constants -- the corpus total and
    # zero -- and publishing them invited the page to narrate an atlas-side
    # defect that no longer exists. `find_unlisted_documents` still runs; it
    # just reports to the console rather than to readers.
    # Two decimals, preformatted: `_fmt` gives floats one, and "2.3 pages"
    # loses the precision the axis argument rests on.
    stats["mean_topics"] = f"{sum(listed) / len(listed):.2f}"
    stats["max_topics"] = max(listed)

    # How wide a single topic reaches across the OTHER axis -- the folder
    # spread of each topic's members. The inverse of `max_topics`, which counts
    # topics per document; this counts folders per topic, and is what the About
    # page means by "a topic draws on as many folders as needed, from one to
    # sixteen". Restricted to documents actually held, the same `in held`
    # discipline `build_tree.build_by_listing` applies, so the page cannot
    # quote a wider spread than the tree it ships beside.
    held_location = {d["doc_id"]: d["location"] for d in documents}
    spreads = []
    for row in listings:
        folders = {held_location[doc_id]
                   for doc_id in row.get("doc_ids") or []
                   if doc_id in held_location}
        if folders:
            spreads.append(len(folders))
    # Only the max is published: the floor is 1 by construction (a topic with
    # no held members is skipped), so tagging it would generate a constant.
    stats["max_topic_folders"] = max(spreads)

    # The Category bag.
    tags = collections.Counter()
    for doc in documents:
        for tag in doc.get("categories") or []:
            tags[tag] += 1
    # Every slug the SITE publishes, suppressed ones included -- the suppression
    # of `/sanskrit/vishhnu/` and `/sanskrit/giitaa/` is our display decision
    # about topic pages, not a fact about the site's vocabulary.
    slugs = {row["slug"] for row in listings}
    for row in listings:
        slugs.update(row.get("aliases") or [])
    # Pre-fold spelling count, from the sidecar: `documents` is already
    # normalized, so this cannot be counted here.
    stats["raw_spellings"] = load_inventory_meta()["raw_category_spellings"]
    stats["categories_unique"] = len(tags)
    stats["categories_matching_a_topic"] = sum(1 for tag in tags if tag in slugs)
    stats["categories_not_matching_a_topic"] = (
        stats["categories_unique"] - stats["categories_matching_a_topic"])
    stats["mean_categories"] = (
        f"{sum(len(d.get('categories') or []) for d in documents) / total:.2f}")
    # Name and count together: quoting "tagged N times" without saying which tag
    # invites the two from drifting apart on the page.
    top_unmatched = max(
        ((n, tag) for tag, n in tags.items() if tag not in slugs),
        default=(0, ""))
    stats["category_not_matching_a_topic_top_count"] = top_unmatched[0]
    stats["category_not_matching_a_topic_top_name"] = top_unmatched[1]

    # The 2020 mirror's corrective, re-derived rather than read back from
    # `changelog.json`: presence in a dated dump proves a document existed by
    # then whatever its `Latest update` claims, and `Latest update` only ever
    # errs late. Must mirror `build_changelog` exactly -- same
    # `load_attestations`, same `parse_update`, same ceiling -- since the page
    # and the chart publish the same correction.
    #
    # The mirror is local-only and not every machine has it, exactly as the
    # Makefile assumes when it passes `--attest` conditionally. But the stat
    # contract needs the key present either way, so an absent mirror keeps the
    # figure already in the page rather than publishing a wrong one: the
    # correction is a fact about the mirror, and a machine that cannot see it
    # has nothing to say about it.
    ceiling = corpus_date(TEXT_LOG_PATH)
    # Both corpora, exactly as the Makefile's `ATTEST` passes them -- a figure
    # here derived from fewer dumps than the chart uses would disagree with the
    # chart it sits beside. Each is included only if its inventory exists, so a
    # machine with neither still runs and keeps whatever the page publishes.
    sources = [(DUMP_2020_INVENTORY_PATH, DUMP_2020_DATE),
               (INVENTORY_PATH, SNAPSHOT_DATE)]
    attested = load_attestations(
        [f"{path}:{date}" for path, date in sources if path.exists()])
    pulled_back = pulled_pre = 0
    cutoff = datetime.datetime.fromisoformat(DUMP_2020_DATE).replace(
        tzinfo=datetime.timezone.utc)
    for doc in documents:
        when = parse_update(doc.get("latest_update") or "", ceiling)
        floor = attested.get(doc["doc_id"])
        # A floor only ever lowers a date -- the bucket is a `min` over the
        # stamp and every attestation -- so adding a corpus can pull a document
        # earlier or leave it alone, never push it later. Checked: zero
        # documents bucket later with both dumps than with the mirror alone.
        if floor is not None and when is not None and floor < when:
            pulled_back += 1
            if floor <= cutoff:
                pulled_pre += 1
    # Documents with no usable date of their own that an earlier corpus can
    # still place. Distinct from `dates_unusable`, which counts broken fields
    # whether or not anything can date them -- the two are equal only while
    # every unusable document happens to sit in one of the dumps.
    stats["bad_dates_rescued"] = sum(
        1 for doc in documents
        if parse_update(doc.get("latest_update") or "", ceiling) is None
        and attested.get(doc["doc_id"]) is not None)
    if attested:
        stats["attested_pulled_back"] = pulled_back
        # Where they land. The mirror is the only corpus that can carry a
        # document across the 2020 line, so this split is also which dump did
        # the work -- and it is why the pre-2020 share is nearly all of it.
        stats["attested_pulled_pre2020_pct"] = round(
            pulled_pre / pulled_back * 100) if pulled_back else 0
        stats["attested_pulled_mid_pct"] = (
            100 - stats["attested_pulled_pre2020_pct"] if pulled_back else 0)

    # Cataloguing.
    stats["languages"] = len(
        {(d.get("language") or "").strip() for d in documents
         if (d.get("language") or "").strip()})
    stats["sanskrit"] = sum(
        1 for d in documents if (d.get("language") or "").strip() == "Sanskrit")
    stats["sanskrit_pct"] = round(stats["sanskrit"] / total * 100, 1)

    # Sizes. Reported in IAST bytes, which is what the tree publishes and what
    # the parent project compares across collections.
    iast = sorted(r["transliterated_bytes"] for r in sizes
                  if r.get("transliterated_bytes"))
    total_iast = sum(iast)
    stats["iast_mb"] = round(total_iast / 1024 / 1024, 1)
    stats["median_kb"] = round(iast[len(iast) // 2] / 1024, 1)
    # How few documents carry a sixth of the corpus -- the Puranas and
    # Monier-Williams against a median of a few KB.
    running, heaviest = 0, 0
    for size in reversed(iast):
        running += size
        heaviest += 1
        if running > total_iast / 6:
            break
    stats["heaviest"] = heaviest

    # Scanned sources, live only -- the same rule `build_tree` publishes under.
    #
    # Intersected with the stems `scans.jsonl` actually names, not just counted
    # off the liveness file. The two drift: `scan_liveness.jsonl` is written by
    # a separate networked stage and outlives a narrowing of the extraction
    # rule, so it currently holds 1012 stems against the 987 scans.jsonl
    # produces. Counting live rows alone publishes 895 where the tree says 873,
    # and a figure on this page disagreeing with the tree is exactly the drift
    # this module exists to prevent.
    live = {r["stem"] for r in liveness if r.get("status") == 200}
    kept = [s for s in scans if s["stem"] in live]
    if kept:
        stats["scans_live"] = len({s["stem"] for s in kept})
        stats["scan_links"] = len(kept)
        # `if s["doc_id"]` matches build_tree.summarize_scans: 32 links
        # carry no document at all, and counting the empty string as one
        # publishes 5,502 against the tree's 5,501.
        stats["scan_docs"] = len({s["doc_id"] for s in kept if s["doc_id"]})

    # The findings, so the prose can quote them without restating a number the
    # audit already computed.
    stats["missing"] = findings["missing"]["count"]
    stats["dead_scans"] = findings["dead_scans"]["count"]
    stats["dates_unusable"] = findings["dates"]["count"]
    # --- two dates, because there are two independent observations ----------
    #
    # The corpus and the scan-liveness check are measured on their own
    # schedules and go stale at their own rates -- 2.5 weeks apart when this
    # was written. One "last audited" date would average them into a claim
    # neither supports. Each is a `str` so `_fmt` passes it through: these are
    # dates, not quantities, and must not acquire thousands separators.
    #
    # `scans_checked` is an EXTERNAL_STAT: this audit does not measure scan
    # liveness, so a machine without that cache leaves the published date
    # exactly as it stands rather than blanking it.
    stats["corpus_date"] = corpus_date_str
    if findings["dead_scans"].get("checked_at"):
        stats["scans_checked"] = findings["dead_scans"]["checked_at"]
    stats.update(field_coverage(documents))

    # Why `subject` is not a browse axis: it is filled on 99.9% of documents
    # and is the same string on most of them, so it separates nothing. A float,
    # so `_fmt` gives it one decimal like every other percentage.
    subjects = collections.Counter(
        (d.get("subject") or "").strip() for d in documents)
    subjects.pop("", None)
    stats["subject_top_pct"] = round(
        subjects.most_common(1)[0][1] / total * 100, 1)

    stats.update(credit_stats(documents))

    # The site renders these with an older Sanscript build instead of
    # Aksharamukha. They are exactly the banner-less pages minus the two
    # metadata-only stubs, which is why `reconstruct_deva` has anything to do:
    # the missing title is a property of that template, not of those documents.
    stats["legacy_translit"] = sum(
        1 for d in documents if d.get("legacy_translit"))

    return stats


# --- rendering --------------------------------------------------------------
#
# Lifted from the e-bharatisampat sibling, which lifted them from wikisource.
# Kept identical on purpose: the three pages should look like one project.


def _esc(s):
    return html.escape(str(s))


def _sa(s):
    """Devanagari gets the site's own font treatment, same as hand-written
    About prose does with `<span class="sa-cap">` -- which
    `docs/translit-static.js` re-renders into the reader's chosen scheme.

    **Only for actual Devanagari.** `translit-static.js` converts on a
    Devanagari code-point run, so wrapping an ITRANS slug like `vishhnu` or
    `z_misc_general` in this class converts nothing and merely styles an
    identifier as if it were Sanskrit prose. Those want `<code>`, which is what
    the hand-written prose around them uses. Unused by the current renderers
    for exactly that reason, and kept for the first finding that does name a
    Devanagari title.
    """
    return f'<span class="sa-cap">{_esc(s)}</span>'


def _doc_link(doc_id, label=None):
    """Link to the document's own page, built as `docs/app.js` does.

    The `~<hash>` suffix is ours, not the site's, so it comes off before the
    URL is built -- linking to it would 404.
    """
    href = f"{SITE_ROOT}/{base_id(doc_id)}.html"
    return (f'<a href="{html.escape(href)}" target="_blank" rel="noopener">'
            f"{_esc(label or doc_id)}</a>")


def _findings_list(items):
    """`items` are already-escaped HTML fragments -- this only wraps them in
    <li>/<ul> and must not re-escape. Indented past its own <summary>'s
    triangle, which the global `.content ul` reset does not clear."""
    lis = "\n".join(f"            <li>{item}</li>" for item in items)
    return f'          <ul style="margin-left: 1.6em;">\n{lis}\n          </ul>'


def _summary_text(description, label):
    """The summary's own content, wrapped in one span.

    `.audit-summary` is `display: flex` (for the triangle), which makes every
    child a flex item -- and flex DISCARDS the whitespace between items. A
    description ending in an element, as ours do when a name is wrapped in
    `<span class="sa-cap">`, would otherwise render as "shiva(34 documents)"
    with the space silently eaten. One wrapper span makes the whole label a
    single flex item, and the space inside it survives.
    """
    return f"<span>{description} ({label})</span>"


def _bullet(description, count, inner_html, unit=None):
    """One finding row. `unit` spells out what the number counts, for cases
    where a bare figure would mislead. A zero-count check still renders, as
    "none found" with an invisible spacer where the triangle would be --
    silence and success must not look the same."""
    if count == 0:
        # Same one-flex-item wrapper as _summary_text, for the same reason.
        return (f'          <li class="audit-item"><div class="audit-summary '
                f'audit-summary-empty"><span>{description}: none found</span></div></li>')
    label = unit if unit is not None else str(count)
    return (
        f'          <li class="audit-item"><details>\n'
        f'            <summary class="audit-summary">{_summary_text(description, label)}</summary>\n'
        f"{inner_html}\n"
        f"          </details></li>"
    )


def _sub_bullet(description, count, inner_html, unit=None):
    """Same construction one level in, for grouping a flat list into
    collapsible sub-groups. Reuses .audit-item/.audit-summary so the triangle
    and spacing match the top-level findings exactly."""
    label = unit if unit is not None else str(count)
    return (
        f'<li class="audit-item"><details>\n'
        f'<summary class="audit-summary">{_summary_text(description, label)}</summary>\n'
        f"{inner_html}\n"
        f"</details></li>"
    )


def _group_ul(items):
    """A nested list of audit bullets -- same wrapper both siblings use
    between a <summary> and its child findings."""
    return ('          <ul style="margin-left: 1.6em; list-style: none; padding-left: 0;">\n'
            + "\n".join(f"            {item}" for item in items)
            + "\n          </ul>")


def _preamble(text_html):
    """One line between a finding's summary and its items.

    The only prose a finding carries. It says what the reader is looking at and
    must stay a single sentence; anything longer is the restated context the
    findings deliberately drop.
    """
    return f'          <p style="margin-left: 1.6em;">{text_html}</p>'


MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")


def _month_name(iso):
    """`2025-02-16` -> `February 2025`. Day precision is dropped: the date
    bounds a diff, and a reader does not need the day the snapshot was taken."""
    try:
        year, month = iso.split("-")[:2]
        return f"{MONTHS[int(month) - 1]} {year}"
    except (ValueError, IndexError):
        return iso


def _as_of(checked_at):
    """A trailing ` Checked <date>.` for a finding a probe measured.

    Empty when the cache carries no stamp, so an unstamped older cache
    publishes its finding undated rather than blank or wrongly dated. The date
    is the PROBE's, never the audit run's -- see `observed_on`.
    """
    if not checked_at:
        return ""
    return f" Checked {_month_name(checked_at)}."


def _capped(items):
    """Trim a long example list, saying so rather than truncating silently."""
    if len(items) <= MAX_EXAMPLES:
        return items
    return items[:MAX_EXAMPLES] + [
        f"<em>… and {len(items) - MAX_EXAMPLES:,} more</em>"]


# --- one renderer per check -------------------------------------------------


def render_missing(finding):
    groups = []
    by_loc = collections.defaultdict(list)
    for doc_id in finding["ids"]:
        by_loc[doc_id.split("/")[0]].append(doc_id)
    for location, ids in sorted(by_loc.items(), key=lambda kv: -len(kv[1])):
        entries = []
        for doc_id in ids:
            slugs = finding.get("on_listing", {}).get(doc_id) or []
            also = ""
            if slugs:
                pages = ", ".join(f"<code>{_esc(s)}</code>" for s in slugs)
                also = f" — also on {pages}"
            entries.append(_doc_link(doc_id, doc_id.split("/", 1)[1]) + also)
        groups.append(_sub_bullet(f"<code>{_esc(location)}</code>",
                                  len(ids), _findings_list(entries)))
    both = finding.get("on_both", 0)
    shared = (f" All {both} are linked from a topic page "
              f"(<code>/sanskrit/&lt;slug&gt;/</code>) as well as from their "
              f"folder page, so both of the site's indexes carry the same "
              f"dead entries." if both == finding["count"] and both else "")
    inner = (_preamble("The site's own indexes link each of these, but "
                       "requesting it returns 404." + shared)
             + "\n" + _group_ul(groups))
    return _bullet("Documents listed but no longer served",
                   finding["count"], inner,
                   unit=f"{finding['count']} documents")


def render_malformed(finding):
    entries = [f"<code>{_esc(d)}</code>" for d in finding["ids"]]
    inner = (_preamble("Bad hrefs on the site's own topic pages — a literal "
                       "space in a path, and a <code>.inf</code> target that "
                       "is not a document.")
             + "\n" + _findings_list(entries))
    return _bullet("Malformed links in the catalogue", finding["count"], inner,
                   unit=f"{finding['count']} entries")


def render_missing_deva(finding):
    entries = [_doc_link(d, d.split("/", 1)[1]) for d in finding["ids"]]
    inner = (_preamble("Only <code>title_deva</code> can be transliterated — "
                       "the English label and the filename stem are both ad-hoc "
                       "romanization — so a document without one cannot render "
                       "in a reader's chosen script. These pages carry no "
                       "Devanāgarī title; the atlas shows an approximation "
                       "rebuilt from the filename, which is lossy where the "
                       "site's spelling cannot express a sound.")
             + "\n" + _findings_list(_capped(entries)))
    return _bullet("Documents without a given Devanāgarī title",
                   finding["count"], inner,
                   unit=f"{finding['count']} documents")


def render_dates(finding):
    groups = []
    if finding["corrupt"]:
        entries = [f"{_doc_link(d, d.split('/', 1)[1])} — <code>{_esc(raw)}</code>"
                   for d, raw in finding["corrupt"]]
        groups.append(_sub_bullet("corrupt", len(finding["corrupt"]),
                                  _findings_list(entries)))
    if finding["blank"]:
        entries = [_doc_link(d, d.split("/", 1)[1]) for d, _ in finding["blank"]]
        groups.append(_sub_bullet("blank", len(finding["blank"]),
                                  _findings_list(entries)))
    inner = (_preamble("<em>Latest update</em> is the only date the corpus "
                       "carries about itself, and on these it is blank or "
                       "unreadable.")
             + "\n" + _group_ul(groups))
    return _bullet("Documents with no usable date", finding["count"], inner,
                   unit=f"{finding['count']} documents")


def render_downloads(finding):
    entries = [f"{_doc_link(d, d.split('/', 1)[1])} — {n} of 7"
               for d, n in finding["items"]]
    # Two kinds in one finding, and the wording has to cover both: a real
    # document missing some PDFs, and a page with nothing to generate them
    # from. The 0-of-7 pair are metadata-only shells -- no `div#article`, no
    # Devanagari -- so "short of the set" would describe them as documents.
    inner = (_preamble("Nearly every document is published as its ITX source "
                       "plus five generated PDFs. The one at 3 of 7 is short "
                       "of the set; the two at 0 of 7 are metadata-only pages "
                       "with no text to generate anything from.")
             + "\n" + _findings_list(entries))
    return _bullet("Documents missing download formats", finding["count"], inner,
                   unit=f"{finding['count']} documents")


def render_dead_scans(finding):
    if finding.get("unchecked"):
        return ('          <li class="audit-item"><div class="audit-summary '
                'audit-summary-empty"><span>Dead scanned-source links: '
                'not checked (run <code>make check-scans</code>)</span></div></li>')
    groups = []
    by_kind = collections.defaultdict(list)
    for stem in finding["stems"]:
        by_kind[finding["detail"][stem]["kind"]].append(stem)
    for kind, stems in sorted(by_kind.items(), key=lambda kv: -len(kv[1])):
        entries = []
        for stem in stems:
            row = finding["detail"][stem]
            status = row.get("status") or row.get("error") or "?"
            entries.append(
                f'<a href="{html.escape(row["url"])}" target="_blank" '
                f'rel="noopener">{_esc(stem)}</a> — <code>{_esc(status)}</code>')
        groups.append(_sub_bullet(_esc(kind), len(stems),
                                  _findings_list(_capped(entries))))
    inner = (_preamble(
        f"Counted by book, not by link: these {finding['count']:,} dead sources "
        f"strand {finding['links']:,} links across {finding['docs']:,} documents, "
        f"because the dead ones are disproportionately heavily-cited anthologies."
        + _as_of(finding.get("checked_at")))
        + "\n" + _group_ul(groups))
    return _bullet("Scanned sources that no longer resolve", finding["count"],
                   inner, unit=f"{finding['count']} books")


def render_suppressed(finding):
    entries = []
    for item in finding["items"]:
        url = f"{SITE_ROOT}/sanskrit/{item['alias']}/"
        kept = f"{SITE_ROOT}/sanskrit/{item['kept']}/"
        entries.append(
            f'<a href="{html.escape(url)}" target="_blank" rel="noopener">'
            f"<code>{_esc(item['alias'])}</code></a> — {_esc(item['note'])} "
            f'<a href="{html.escape(kept)}" target="_blank" rel="noopener">'
            f"<code>{_esc(item['kept'])}</code></a>")
    inner = (_preamble(
        "The site publishes these as separate topic pages, but each says "
        "nothing its counterpart does not. The tree shows the one named "
        "second; these names reach it too.")
        + "\n" + _findings_list(entries))
    return _bullet("Topic pages the site duplicates", finding["count"],
                   inner, unit=f"{finding['count']} pages")


def render_unlisted(finding):
    groups = []
    for base, ids in finding["pairs"].items():
        entries = [_doc_link(d, d.split("/", 1)[1]) for d in ids]
        groups.append(_sub_bullet(_esc(base.split("/", 1)[-1]), len(ids),
                                  _findings_list(entries)))
    inner = (_preamble(
        "Each is half of a pair whose ids differ only by letter case, which "
        "macOS and Windows collapse into one file. Both pages were fetched and "
        "both are in the tree — but the id reaching the tree is not the id the "
        "site uses, so the join against the topic pages misses. This is ours "
        "to fix, in whatever mints the id.")
        + "\n" + _group_ul(groups))
    return _bullet("Documents the topics axis drops", finding["count"],
                   inner, unit=f"{finding['count']} documents")


# The registry. Adding a check is one entry here plus its two functions.
UPSTREAM_CHECKS = [
    ("suppressed", render_suppressed),
    ("missing", render_missing),
    ("malformed", render_malformed),
    ("missing_deva", render_missing_deva),
    ("dates", render_dates),
    ("downloads", render_downloads),
    ("dead_scans", render_dead_scans),
]

# Runs and prints, but is NOT published -- see `render_audit_html`. The audit
# page is about the source collection; our own defects belong in the console,
# where they reach the person who can fix them.
OURS_CHECKS = [
    ("unlisted", render_unlisted),
]


def render_topic_folders(documents, listings):
    """The "Which folders each topic draws on" table.

    Was hand-written HTML sitting OUTSIDE the AUDIT region, and had drifted:
    17 of its 85 rows overstated their doc count, every one of them from
    before the 25 documents the site 404s stopped being held. Exactly the
    failure the data-stat contract exists to prevent, one level up -- a whole
    table rather than a single figure -- so it is generated here now.

    Counts only documents actually held, the same `in held` discipline
    `build_tree.build_by_listing` applies, so a row can never claim more
    documents than the tree ships.
    """
    held = {d["doc_id"]: d["location"] for d in documents}
    rows = []
    for row in listings:
        docs = [d for d in row.get("doc_ids") or [] if d in held]
        if not docs:
            continue
        folders = collections.Counter(held[d] for d in docs)
        rows.append((row["slug"], len(docs), folders))
    rows.sort(key=lambda r: (-r[1], r[0]))

    cell = 'padding:2px 12px 2px 0;'
    num = 'padding:2px 12px 2px 0; text-align:right;'
    body = []
    for slug, count, folders in rows:
        top = folders.most_common(3)
        # `doc_` stripped: every folder carries it, so it is noise in a column
        # of folder names, and the prose around this table already writes them
        # bare (`devii`, `deities_misc`).
        parts = [f"<code>{_esc(name.removeprefix('doc_'))}</code>"
                 f"&nbsp;{round(n / count * 100)}%"
                 for name, n in top]
        if len(folders) > len(top):
            parts.append(f'<span style="opacity:.6;">+{len(folders) - len(top)} more</span>')
        body.append(
            f'                <tr><td style="{cell}"><code>{_esc(slug)}</code></td>'
            f'<td style="{num}">{count:,}</td>'
            f'<td style="{num}">{len(folders)}</td>'
            f'<td style="padding:2px 0;">{"; ".join(parts)}</td></tr>')

    head = (
        '                <tr style="border-bottom:1px solid var(--border);">\n'
        f'                  <th style="{cell} text-align:left;">topic</th>\n'
        f'                  <th style="{num}">docs</th>\n'
        f'                  <th style="{num}">folders</th>\n'
        '                  <th style="padding:2px 0; text-align:left;">drawn from</th>\n'
        "                </tr>")
    table = (
        '          <div style="overflow-x:auto;">\n'
        '            <table style="border-collapse:collapse; font-size:13px; margin:0 0 4px;">\n'
        f"              <thead>\n{head}\n              </thead>\n"
        "              <tbody>\n" + "\n".join(body) + "\n              </tbody>\n"
        "            </table>\n"
        "          </div>")
    return (
        '        <ul style="list-style: none; padding-left: 0; margin: 0;">\n'
        '          <li class="audit-item"><details>\n'
        '            <summary class="audit-summary"><span>Which folders each '
        "topic draws on</span></summary>\n"
        f"{table}\n"
        "          </details></li>\n"
        "        </ul>")


def render_audit_html(findings):
    """The published region: upstream findings only.

    `OURS_CHECKS` is deliberately not rendered. The audit's subject is the
    source collection -- what a reader could go fix on sanskritdocuments.org --
    and a section reporting our own defects (or, once fixed, reporting none)
    is noise against that purpose. Those checks still run and still print to
    the console, where the person who can act on them will see them.
    """
    upstream = [render(findings[key]) for key, render in UPSTREAM_CHECKS]
    return (
        '        <h3 id="opportunities-for-correction">Opportunities for Correction</h3>\n'
        "        <p>\n"
        "          The Atlas codebase also includes an audit pipeline for\n"
        "          detecting and concisely indicating problems that should be fixed on\n"
        "          sanskritdocuments.org. Every figure below is re-derived by the run\n"
        "          that publishes it.\n"
        "        </p>\n"
        '        <ul style="list-style: none; padding-left: 0;">\n'
        + "\n".join(upstream)
        + "\n        </ul>"
    )


# --- writing back -----------------------------------------------------------


def update_about_region(name, new_html, path=ABOUT_HTML_PATH):
    """Replace the block between one pair of `<!-- NAME:START/END -->` markers.

    A targeted string splice, not an HTML parse, so the rest of the file and
    the markers themselves are untouched. `name` selects the region: AUDIT for
    the Data Quality findings, TOPIC_FOLDERS for the folders-per-topic table.
    """
    start_marker = MARKERS[name][0]
    end_marker = MARKERS[name][1]
    text = path.read_text(encoding="utf-8")
    try:
        start = text.index(start_marker) + len(start_marker)
        end = text.index(end_marker)
    except ValueError as err:
        raise SystemExit(
            f"{path} has no {name}:START/{name}:END markers -- add them around "
            f"the region before running with --update-about"
        ) from err
    path.write_text(text[:start] + "\n" + new_html + "\n        " + text[end:],
                    encoding="utf-8")


def update_about_html(new_html, path=ABOUT_HTML_PATH):
    """Back-compat wrapper for the AUDIT region."""
    update_about_region("AUDIT", new_html, path)


def _fmt(value):
    """Integers get thousands separators; rates keep one decimal.

    Percentages and ratios are floats and must not be comma-grouped, rounded
    to int, or stripped of a trailing zero -- a coverage rate of 100.0% would
    publish as "100" and read as a count, and a ratio of 1.87 would round to
    "2". A stat that genuinely wants a whole number says so by being an int at
    the computation site, rather than by loosening this.
    """
    if isinstance(value, str):
        return value  # already formatted at the computation site
    if isinstance(value, int):
        return f"{value:,}"
    return f"{value:.3f}" if abs(value) < 1 else f"{value:,.1f}"


def update_intro_stats(stats, path=ABOUT_HTML_PATH):
    """Rewrite each `data-stat="..."` figure in the hand-written prose.

    Per-element substitution rather than a marker region: these numbers sit
    inside authored sentences, so there is no contiguous block to splice. The
    tag is the contract -- prose around it can be rewritten freely, and only
    the digits between the tagged element's own `>`/`<` are replaced.

    A tag naming a stat we do not compute, or a stat with no tag, is an error
    rather than a skip: silently leaving a stale figure on the page is exactly
    the failure this replaces.
    """
    text = path.read_text(encoding="utf-8")
    seen = set()

    def sub(match):
        key = match.group("key")
        if key not in stats:
            if key in EXTERNAL_STATS or key in MIRROR_STATS:
                # Offline run, or no local mirror -- leave the measured value.
                return match.group(0)
            raise SystemExit(
                f'{path} tags data-stat="{key}", which the audit does not compute'
            )
        seen.add(key)
        return f"{match.group('open')}{_fmt(stats[key])}{match.group('close')}"

    pattern = re.compile(
        r'(?P<open><(?P<tag>span|text)\b[^>]*\bdata-stat="(?P<key>[^"]+)"[^>]*>)'
        r"[^<]*"
        r"(?P<close></(?P=tag)>)"
    )
    updated = pattern.sub(sub, text)

    # Write BEFORE validating the reverse direction. The check below is about
    # the *next* edit -- a figure that has drifted out of the prose -- while
    # `updated` already holds correct values for every tag that is present.
    # Raising first discarded the whole substitution, so from the commit that
    # introduced this stage until 2026-08-24 no data-stat figure was ever
    # written and every number on the page was still the hand-typed one.
    path.write_text(updated, encoding="utf-8")

    # EXTERNAL_STATS are exempt in BOTH directions. `sub` already leaves such a
    # tag alone when an offline run did not measure it; the same figures must
    # not be *required* to have a tag, or the page can never satisfy both rules
    # at once.
    missing = sorted(set(stats) - seen - EXTERNAL_STATS)
    if missing:
        raise SystemExit(
            f"{path} has no data-stat tag for: {', '.join(missing)} -- "
            f"tag the figure in the prose or drop it from intro_stats()"
        )
    return len(seen)  # distinct stats published, not tag sites


# --- report -----------------------------------------------------------------


def print_report(findings, stats):
    print(f"audit of {stats['total']:,} documents "
          f"({datetime.date.today().isoformat()})\n")
    rows = [
        ("listed but not served", findings["missing"]["count"]),
        ("malformed catalogue hrefs", findings["malformed"]["count"]),
        ("no Devanagari title", findings["missing_deva"]["count"]),
        ("no usable date", findings["dates"]["count"]),
        ("incomplete download set", findings["downloads"]["count"]),
        ("dead scanned sources", findings["dead_scans"]["count"]),
        ("duplicate topic pages", findings["suppressed"]["count"]),
    ]
    print("  upstream, fixable on sanskritdocuments.org")
    for label, count in rows:
        print(f"    {count:>6,}  {label}")
    unlisted = findings["unlisted"]
    print("\n  ours")
    # `explained` is vacuously true at zero, so guard on the count too --
    # otherwise a clean run annotates nothing as "all case-collision pairs".
    note = (" (all case-collision pairs)"
            if unlisted["count"] and unlisted["explained"] else "")
    print(f"    {unlisted['count']:>6,}  dropped by the topics axis{note}")
    dead = findings["dead_scans"]
    if not dead.get("unchecked") and dead["count"]:
        print(f"\n  dead scans strand {dead['links']:,} links across "
              f"{dead['docs']:,} documents")


# --- entry point ------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--update-about", action="store_true",
                        help="rewrite the AUDIT region and the data-stat "
                             "figures in docs/about.html")
    args = parser.parse_args()

    documents = load_documents()
    listings = load_listings()
    catalogue = load_catalogue()
    sizes = load_sizes()
    scans = load_scans()
    liveness = load_liveness()
    ceiling = fetch_ceiling()

    findings = {
        "missing": find_missing_documents(documents, catalogue, listings),
        "malformed": find_malformed_hrefs(catalogue),
        "missing_deva": find_missing_deva_titles(documents),
        "dates": find_unparseable_dates(documents, ceiling),
        "downloads": find_incomplete_downloads(documents),
        "dead_scans": find_dead_scans(scans, liveness),
        "unlisted": find_unlisted_documents(documents, listings),
        "suppressed": find_suppressed_listings(listings),
    }
    # The scrape date, from the journal `build_tree` stamps
    # `__content_version__` from -- so the About page and the topbar cannot
    # disagree about when the corpus was taken.
    stats = intro_stats(documents, listings, catalogue, sizes, scans,
                        liveness, findings, ceiling.date().isoformat())

    print_report(findings, stats)

    if args.update_about:
        update_about_html(render_audit_html(findings))
        print(f"\nwrote the audit region of {ABOUT_HTML_PATH}")
        update_about_region("TOPIC_FOLDERS",
                            render_topic_folders(documents, listings))
        print("wrote the folders-per-topic table")
        tagged = update_intro_stats(stats)
        print(f"refreshed {tagged} figures in the same file")


if __name__ == "__main__":
    main()
